### ISSUE TITLE
Heads up on Flutter Master - Breaking changes

### ISSUE THREAD

**Issue by dupiesdupreez** [smaho-engineering/weekday_selector#3]
Just a heads up on the Flutter master branch, the weekday selector breaks.

![image](https://user-images.githubusercontent.com/6910085/89562227-eff7d500-d819-11ea-82fa-93fdac7c00f2.png)

**Comment by vargavince91** [comment]
Thank you for the heads-up. I think in this case, updating the weekday selector package will resolve your issue.

Can you please update the package to the latest version? We fixed the `Diagnosticable` vs `DiagnosticableMixin` issues there already (see [changelog](https://pub.dev/packages/weekday_selector/changelog) for more info).

 https://github.com/smaho-engineering/weekday_selector/blob/master/lib/src/weekday_selector_theme.dart#L22

**Comment by dupiesdupreez** [comment]
Perfect thank you
