### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by DHjeelm** [smaho-engineering/weekday_selector#5]
Hi

I get the following error code when i implement your example code and i don't no what to do:

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _CastError was thrown building WeekdayButton(dirty, dependencies:
[_LocalizationsScope-[GlobalKey#38875], _InheritedTheme]):
Null check operator used on a null value

The relevant error-causing widget was:
  WeekdayButton
  file:///Users/daniel/.pub-cache/hosted/pub.dartlang.org/weekday_selector-1.0.0/lib/src/weekday_selecto
  r.dart:251:12

When the exception was thrown, this was the stack:
#0      WeekdayButton.build (package:weekday_selector/src/weekday_selector.dart:459:40)
#1      StatelessElement.build (package:flutter/src/widgets/framework.dart:4569:28)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#4      StatelessElement.update (package:flutter/src/widgets/framework.dart:4576:5)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#6      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5503:32)
#7      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6105:17)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#10     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#12     StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#18     StatelessElement.update (package:flutter/src/widgets/framework.dart:4576:5)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#20     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5503:32)
#21     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6105:17)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#29     StatelessElement.update (package:flutter/src/widgets/framework.dart:4576:5)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#33     ProxyElement.update (package:flutter/src/widgets/framework.dart:4843:5)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#39     StatelessElement.update (package:flutter/src/widgets/framework.dart:4576:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#43     StatelessElement.update (package:flutter/src/widgets/framework.dart:4576:5)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#47     ProxyElement.update (package:flutter/src/widgets/framework.dart:4843:5)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#50     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#51     ProxyElement.update (package:flutter/src/widgets/framework.dart:4843:5)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#53     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5503:32)
#54     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6105:17)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#57     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#58     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#59     StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#63     ProxyElement.update (package:flutter/src/widgets/framework.dart:4843:5)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#66     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#67     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#68     StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#70     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#73     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#74     StatelessElement.update (package:flutter/src/widgets/framework.dart:4576:5)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#76     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#79     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#81     StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#84     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#86     StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#89     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#90     ProxyElement.update (package:flutter/src/widgets/framework.dart:4843:5)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#93     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#94     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#95     StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#98     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#100    StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#102    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#105    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#106    StatelessElement.update (package:flutter/src/widgets/framework.dart:4576:5)
#107    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#108    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
#109    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#110    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
#111    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#113    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#114    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#115    StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#117    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5503:32)
#118    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6105:17)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#121    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#122    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#123    StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#125    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
#126    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#128    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#129    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#130    StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#131    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#132    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
#133    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#135    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#136    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#137    StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#138    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#139    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
#140    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#142    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#143    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#144    StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#146    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#147    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#148    StatelessElement.update (package:flutter/src/widgets/framework.dart:4576:5)
#149    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#151    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#152    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#153    StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#154    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#155    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
#156    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#158    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#159    ProxyElement.update (package:flutter/src/widgets/framework.dart:4843:5)
#160    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:181:11)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#162    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
#163    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#165    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#166    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#167    StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#168    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#169    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#170    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#171    ProxyElement.update (package:flutter/src/widgets/framework.dart:4843:5)
#172    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#173    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#174    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#175    ProxyElement.update (package:flutter/src/widgets/framework.dart:4843:5)
#176    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#178    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#179    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#180    StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#181    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#182    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#183    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#184    StatelessElement.update (package:flutter/src/widgets/framework.dart:4576:5)
#185    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#186    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#187    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#188    StatelessElement.update (package:flutter/src/widgets/framework.dart:4576:5)
#189    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#190    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
#191    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#192    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#193    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#194    ProxyElement.update (package:flutter/src/widgets/framework.dart:4843:5)
#195    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#197    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#198    ProxyElement.update (package:flutter/src/widgets/framework.dart:4843:5)
#199    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#200    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#201    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#202    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#203    StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#204    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#205    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#206    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#207    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#208    StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#209    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#210    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#211    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#212    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#213    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2694:33)
#214    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:873:21)
#215    RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:319:5)
#216    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#217    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#218    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure>
(package:flutter/src/scheduler/binding.dart:865:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: Null check operator used on a null value

Another exception was thrown: Null check operator used on a null value

Another exception was thrown: Null check operator used on a null value

Another exception was thrown: Null check operator used on a null value

Another exception was thrown: Null check operator used on a null value

Another exception was thrown: Null check operator used on a null value
       ⢿
Another exception was thrown: A RenderFlex overflowed by 699786 pixels on the right.

Another exception was thrown: A RenderFlex overflowed by 87 pixels on the bottom.
        
Reloaded 0 libraries in 286ms.

**Comment by tyler-jewell** [comment]
Also having this same issue.

**Comment by tyler-jewell** [comment]
@DHjeelm found the root cause. If you have a "buttonTheme" defined in the main MaterialApp, you must have a "ColorScheme" defined as this is what is causing the error if null. Either define it in your buttonTheme, or use the default buttonTheme. Here's what I have:

```
return GetMaterialApp(
      initialBinding: GlobalBindings(),
      defaultTransition: Transition.fade,
      transitionDuration: Get.defaultTransitionDuration,
      enableLog: true,
      theme: ThemeData.light().copyWith(
        textButtonTheme: TextButtonThemeData(style: textButtonStyle),
        buttonTheme: ButtonThemeData(
          buttonColor: AppColorTheme.brand[700],
          colorScheme: ColorScheme.fromSwatch(),
        ),
        bottomNavigationBarTheme: BottomNavigationBarThemeData(
          selectedItemColor: AppColorTheme.brand[700],
        ),
        primaryColor: AppColorTheme.brand[700],
        floatingActionButtonTheme: FloatingActionButtonThemeData(
          backgroundColor: AppColorTheme.accent,
        ),
        appBarTheme: AppBarTheme(
          backgroundColor: AppColorTheme.brand[700],
        ),
        textTheme: AppTextTheme.main,
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: primaryRaisedButtonStyle,
        ),
      ),
      darkTheme: ThemeData.dark().copyWith(textTheme: AppTextTheme.main),
      themeMode: ThemeMode.light,
      navigatorObservers: [observer],
      initialRoute: '/',
      getPages: appPages,
      debugShowCheckedModeBanner: false,
    );
```
