### ISSUE TITLE
Unable to get all selected days once. 

### ISSUE THREAD

**Issue by irfan-429** [smaho-engineering/weekday_selector#6]
Hi, I want to get all selected days once but unable to find a function that could do this job for me until I go manually with my own way.

**Comment by vincevargadev** [comment]
That is the correct way, you are doing it correctly.

The package just displays the weekday selector. This package and its widgets don't maintain the state of selected days, you do. It's designed to behave similarly as other widgets in Flutter work (for example the `CheckboxListTile`, or `RadioListTile`).
