### ISSUE TITLE
How can I change the U.I from circular to checkbox 

### ISSUE THREAD

**Issue by debjeetdebnath** [smaho-engineering/weekday_selector#7]
Hello, Nice package though it is very helpful.
so, I want to have checkbox instead being circular.
how can I do that and I want to select the checkbox 1 by 1.

**Comment by debjeetdebnath** [comment]
@vincevargadev Hello, I achieve one by one selection of days by using 
onChanged: (v) {
            printIntAsDay(v);
            setState(() {
              values[v % 7] = !values[v % 7];
            });
          },
          
          but I am still struck at how can I introduce checkbox!

**Comment by debjeetdebnath** [comment]
![I want to have like this ](https://user-images.githubusercontent.com/58223584/194711393-f45b7251-39c0-4c11-ada5-169bd5943f65.png)

**Comment by debjeetdebnath** [comment]
![I want ui like this ](https://user-images.githubusercontent.com/58223584/194711429-507f2c23-f945-45fd-a2a7-36b292e7943c.png)

**Comment by vincevargadev** [comment]
You can probably approach this issue with [`Checkbox`](https://api.flutter.dev/flutter/material/Checkbox-class.html). The `weekday_selector` library currently doesn't support what you described as IMO it can be more conveniently implemented using plain old Flutter `Checkbox`.
